spring:
  kafka:
    bootstrap-servers: 192.168.0.100:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: 192.168.0.100:9092
    consumer:
      bootstrap-servers: 192.168.0.100:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: '@postgres!'
  jpa:
    hibernate:
      ddl-auto: create
#      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true